version: '3.7'

services:
  web:
    container_name: web-dev
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./app/:/usr/src/CurrencyExchange/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres-db
    restart: always
    image: postgres:10.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Actimel13
      - POSTGRES_DB=currency_ex
#    ports:
#      - "5432:5432"
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    container_name: worker
    restart: always
    command: celery -A CurrencyExchange.celery worker --loglevel=info
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - redis
      - postgres
volumes:
  postgres_data:

