version: '3.7'

services:
  web:
    build: ./CurrencyExchange
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/CurrencyExchange/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:10.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Actimel13
      - POSTGRES_DB=currency_ex
    ports:
      - "5433:5433"
  redis:
    image: redis
    ports:
      - "6379:6379"

